name: ocr
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-378.0.dev <4.0.0'

dependencies:
  camera: ^0.10.4
  flutter:
    sdk: flutter
  google_mlkit_commons: ^0.2.0
  google_mlkit_text_recognition: ^0.5.0
  google_mlkit_translation: ^0.5.0
  http: ^0.13.5
  image_cropper: ^3.0.2
  image_picker: ^0.8.7+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
